name: Setup ROCm host

description: Set up ROCm host for CI

runs:
  using: composite
  steps:
    - name: Clean workspace
      shell: bash
      run: |
        rm -rf "${GITHUB_WORKSPACE}"
        mkdir "${GITHUB_WORKSPACE}"
    - name: Set DOCKER_HOST
      shell: bash
      run: echo "DOCKER_HOST=unix:///run/user/$(id -u)/docker.sock" >> "${GITHUB_ENV}"
    - name: Runner health check system info
      if: always()
      shell: bash
      run: |
        cat /etc/os-release || true
        cat /etc/apt/sources.list.d/rocm.list || true
        cat /opt/rocm/.info/version || true
        whoami
    - name: Runner health check rocm-smi
      if: always()
      shell: bash
      run: |
        rocm-smi
    - name: Runner health check rocminfo
      if: always()
      shell: bash
      run: |
        rocminfo
    - name: Runner health check GPU count
      if: always()
      shell: bash
      run: |
        ngpu=$(rocminfo | grep -c -E 'Name:.*\sgfx')
        if [[ "x$ngpu" != "x2" && "x$ngpu" != "x4" ]]; then
            echo "Failed to detect GPUs on the runner"
            exit 1
        fi
    - name: Runner health check disconnect on failure
      if: ${{ failure() }}
      shell: bash
      run: |
        killall runsvc.sh
    - name: Preserve github env variables for use in docker
      shell: bash
      run: |
        env | grep '^GITHUB' > "/tmp/github_env_${GITHUB_RUN_ID}"
