name: pull

on:
  pull_request:
  push:
    branches:
      - master

env:
  IN_CI: 1 # TODO delete in favor of GITHUB_ACTIONS
  IS_GHA: 1 # TODO delete in favor of GITHUB_ACTIONS

jobs:
  linux-xenial-py3_7-gcc5_4:
    name: linux-xenial-py3.7-gcc5.4
    uses: ./.github/workflows/_linux-build-test.yml
    with:
      build-environment: linux-xenial-py3.7-gcc5.4
      docker-image-base: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-py3.7-gcc5.4
      build-generates-artifacts: true
      build-docs: true
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 2, runner: "linux.2xlarge" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.2xlarge" },
          { config: "distributed", shard: 1, num_shards: 1, runner: "linux.2xlarge" },
          { config: "docs_test", shard: 1, num_shards: 1,  runner: "linux.2xlarge" },
          { config: "backwards_compat", shard: 1, num_shards: 1, runner: "linux.2xlarge" },
          { config: "jit_legacy", shard: 1, num_shards: 1, runner: "linux.2xlarge" }
        ]}

  linux-xenial-cuda11_3-py3_7-gcc7:
    name: linux-xenial-cuda11.3-py3.7-gcc7
    uses: ./.github/workflows/_linux-build-test.yml
    with:
      build-environment: linux-xenial-cuda11.3-py3.7-gcc7
      docker-image-base: 308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-xenial-cuda11.3-cudnn8-py3-gcc7
      build-generates-artifacts: true
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 2, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "default", shard: 2, num_shards: 2, runner: "linux.4xlarge.nvidia.gpu" },
          { config: "distributed", shard: 1, num_shards: 1, runner: "linux.8xlarge.nvidia.gpu" }
        ]}
