name: android-tests

on:
  pull_request:
  workflow_dispatch:
  push:

jobs:

  build:
    runs-on: macos-11
    env:
      JOB_BASE_NAME: macos-11-android-tests
    steps:
      - name: print labels
        run: echo "Hello!"

      - name: Checkout PyTorch
        uses: zhouzhuojie/checkout@05b13c9a0d21f08f6d5e64a1d5042246d13619d9
        with:
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0
          submodules: recursive

      - name: build PyTorch Android
        run: |
          export ANDROID_NDK=/Users/runner/Library/Android/sdk/ndk-bundle
          ./scripts/build_pytorch_android.sh x86

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: /android/run_tests.sh
