name: trunk

on:
  # TODO remove this
  pull_request:
  push:
    branches:
      - master

env:
  IN_CI: 1 # TODO delete in favor of GITHUB_ACTIONS
  IS_GHA: 1 # TODO delete in favor of GITHUB_ACTIONS

jobs:
  pytorch-xla-linux-bionic-py3_7-clang8-build:
    name:  pytorch-xla-linux-bionic-py3.7-clang8
    uses: ./.github/workflows/_linux-build.yml
    with:
      build-environment: pytorch-xla-linux-bionic-py3.7-clang8
      docker-image-name: xla_base

  pytorch-xla-linux-bionic-py3_7-clang8-test:
    name: pytorch-xla-linux-bionic-py3.7-clang8
    uses: ./.github/workflows/_linux-test.yml
    needs: pytorch-xla-linux-bionic-py3_7-clang8-build
    with:
      build-environment: pytorch-xla-linux-bionic-py3.7-clang8
      docker-image: ${{ needs.pytorch-xla-linux-bionic-py3_7-clang8-build.outputs.docker-image }}
      test-matrix: |
        { include: [
          { config: "default", shard: 1, num_shards: 1, runner: "linux.2xlarge" },
        ]}
